on:
  workflow_dispatch:
  push:
    branches:
    - master
    paths:
    - 'packages/plugin-compat/**'
    - '!packages/plugin-compat/sources/extensions.ts'
  pull_request:
    paths:
    - 'packages/plugin-compat/**'
    - '!packages/plugin-compat/sources/extensions.ts'

name: 'plugin-compat'
jobs:
  plugin-compat:
    name: 'Testing plugin-compat'
    runs-on: arc-runner-set

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/actions/prepare

    - name: 'Run the plugin-compat tests'
      run: |
        node ./scripts/run-yarn.js test:plugin-compat
    - name: 'Check Runner Info'
      run: |
          echo "Running on GCP VM inside K3s!"
          hostname
          uname -a
    - name: 'Display System Specs'
      run: |
          echo "------------------ CPU Info ------------------"
          echo "CPU Threads: $(nproc)"
          lscpu | grep 'Model name'
          
          echo "------------------ Memory Info ------------------"
          free -h
          
          echo "------------------ Disk Space ------------------"
          df -h /
